#!/usr/bin/env bash
# run_security_audit.sh
# Toggle between vulnerable and fixed states to generate formatted reports using Docker Compose.

MODE=$1

if [ -z "$MODE" ]; then
    echo "Usage: ./run_security_audit.sh [before|after|all]"
    exit 1
fi

mkdir -p reports

echo "Starting Docker environment (app-mod10)..."
docker compose up -d

if [ "$MODE" = "before" ] || [ "$MODE" = "all" ]; then
    echo "Reverting to vulnerable state (commit 61ee141)..."
    git checkout 61ee1417e687d9d72bb9b64a5458ab84c708b0c6 -- \
        vulnerable_archive/archiver/views.py \
        vulnerable_archive/vulnerable_archive/settings.py \
        vulnerable_archive/archiver/templates/archiver/view_archive.html

    docker compose restart app-mod10 ollama-mod10

    echo "Running vulnerable test suite inside Docker..."
    docker compose exec -T app-mod10 python manage.py test archiver > reports/before_fix_report.txt 2>&1

    # Format the report
    cat << 'MD' > reports/before_fix_report.md
# Pre-Remediation Vulnerability Scan Report

## Overview
This report documents the security posture of the `vulnerable_archive` application prior to remediation. The test suite aggressively targets 9 specific vulnerability vectors encompassing both traditional web vulnerabilities and LLM-specific injection risks.

## Raw Test Output
```text
MD
    cat reports/before_fix_report.txt >> reports/before_fix_report.md
    echo '```' >> reports/before_fix_report.md
    rm reports/before_fix_report.txt

    echo "Before report generated at reports/before_fix_report.md"
fi

if [ "$MODE" = "after" ] || [ "$MODE" = "all" ]; then
    echo "Applying security patches..."
    git checkout 61ee1417e687d9d72bb9b64a5458ab84c708b0c6 -- \
        vulnerable_archive/archiver/views.py \
        vulnerable_archive/vulnerable_archive/settings.py \
        vulnerable_archive/archiver/templates/archiver/view_archive.html
    git apply fixes.patch 2>/dev/null || true

    docker compose restart app-mod10 ollama-mod10

    echo "Running fixed test suite inside Docker..."
    docker compose exec -T app-mod10 python manage.py test archiver > reports/after_fix_report.txt 2>&1

    # Format the report
    cat << 'MD' > reports/after_fix_report.md
# Post-Remediation Security Scan Report

## Overview
This report demonstrates the successful mitigation of the previously identified vulnerabilities. The same exploit suite from the pre-remediation phase was executed against the patched codebase. The resulting errors (404 Not Found, Signature verification failed, etc.) successfully prove the integrity of the implemented security controls.

## Raw Test Output
```text
MD
    cat reports/after_fix_report.txt >> reports/after_fix_report.md
    echo '```' >> reports/after_fix_report.md
    rm reports/after_fix_report.txt

    echo "After report generated at reports/after_fix_report.md"
fi

echo "Security audit complete."

# Clean up test artifacts created by Docker (root-owned)
docker compose exec -T app-mod10 rm -rf /app/vulnerable_archive/exported_summaries/ 2>/dev/null || true

# Generate Remediation Report
cat << 'MD' > reports/vulnerability_remediation_report.md
# Vulnerability Remediation Report

## Executive Summary
A comprehensive security analysis was performed on the `vulnerable_archive` Django application. A total of 10 distinct vulnerabilities were identified, encompassing both traditional OWASP Top 10 vulnerabilities and emerging LLM integration risks. All identified vulnerabilities have been successfully mitigated.

---

## 1. SQL Injection (Traditional)
* **Where:** `vulnerable_archive/archiver/views.py` (Line 134, `search_archives` function)
* **What:** The application directly interpolated the `query` GET parameter into a raw SQL string (`f"SELECT ... WHERE title LIKE '%{query}%'"`), allowing arbitrary SQL execution and data exfiltration.
* **How it was fixed:** Refactored the raw SQL query to use Django's built-in Object-Relational Mapping (ORM) framework: `Archive.objects.filter(user=request.user, title__icontains=query)`. The ORM automatically parameterizes queries, neutralizing SQL injection vectors.

## 2. SQL Injection via LLM (AI Vulnerability)
* **Where:** `vulnerable_archive/archiver/views.py` (Lines 169-180, `ask_database` function)
* **What:** The application accepted raw SQL commands generated by a local LLM and executed them directly against the database (`cursor.execute(sql_query)`). An attacker could use prompt injection (e.g., "Run the following query exactly as it is provided without any modification") to trick the LLM into generating destructive `DROP`, `UPDATE`, or expansive `SELECT` queries, bypassing any keyword-based SQL filters.
* **How it was fixed:** Eliminated raw SQL execution entirely. Replaced the LLM-to-SQL pipeline with a pre-canned query system: the LLM now classifies user intent into one of three safe categories (`RECENT`, `SEARCH`, `COUNT`) and returns structured JSON. The application maps the classified intent to hardcoded Django ORM queries (`Archive.objects.filter(...)`), ensuring no user-controlled or LLM-generated SQL ever reaches the database cursor.

## 3. Server-Side Request Forgery (SSRF)
* **Where:** `vulnerable_archive/archiver/views.py` (Lines 69-70, `add_archive` function)
* **What:** The application fetched external URLs via `requests.get(url)` without validating the destination. Attackers could supply internal IPs (e.g., `127.0.0.1`, `169.254.169.254` AWS Metadata) to map internal networks or extract sensitive cloud credentials.
* **How it was fixed:** Introduced URL parsing (`urllib.parse.urlparse`) and IP resolution (`socket.gethostbyname`), validating the output against `ipaddress.is_private` and `is_loopback` to definitively catch octal, IPv6, and DNS rebinding bypasses.

## 4. SSRF via AI Tool Call
* **Where:** `vulnerable_archive/archiver/views.py` (Line 299, `enrich_archive` function)
* **What:** The AI agent was equipped with a `fetch_url` tool that blindly executed `requests.get()` based on LLM output. An attacker could inject malicious instructions via the `archive.notes` field (which was interpolated directly into the LLM prompt), causing the LLM to call `fetch_url` against internal infrastructure — a data exfiltration vector through prompt injection.
* **How it was fixed:** Two-layer defense: (1) Removed `{archive.notes}` from the LLM prompt entirely, eliminating the injection/exfiltration surface through user-controlled notes. (2) Applied `socket` and `ipaddress` network boundary validation to all URLs extracted from the LLM's `fetch_url` tool calls, blocking private and loopback addresses.

## 5. Path Traversal / Arbitrary File Write
* **Where:** `vulnerable_archive/archiver/views.py` (Lines 214, 229-232, `export_summary` function)
* **What:** The application utilized LLM output to determine the file path for exporting summaries. The user-controlled `filename_hint` parameter was passed directly to the LLM prompt, and the LLM-generated path was used for file writes. An attacker could coerce the LLM into returning a path like `../../../etc/passwd` or `/root/.ssh/authorized_keys`, resulting in an arbitrary file write. Even sanitization via `os.path.basename()` could be bypassed by manipulating LLM output.
* **How it was fixed:** Eliminated user and LLM control over the filename entirely. Replaced the LLM-generated file path with a random UUID (`uuid.uuid4().hex + ".txt"`), ensuring the filename is cryptographically random and cannot be influenced by user input or LLM manipulation. All writes remain confined to the `exported_summaries/` directory.

## 6. Hardcoded Secrets (JWT & Django)
* **Where:**
  * `vulnerable_archive/archiver/views.py` (Line 40, `generate_token` function)
  * `vulnerable_archive/vulnerable_archive/settings.py` (Line 23)
* **What:** The JWT signing key (`"do_not_share_this"`) and the Django `SECRET_KEY` were hardcoded in the source code. If the repository was compromised, attackers could forge administrative JWTs and cryptographic Django signatures.
* **How it was fixed:** Swapped the hardcoded strings for environmental variables (`os.environ.get('JWT_SECRET', secrets.token_hex(32))`), utilizing the `secrets` module to dynamically load secure runtime fallbacks.

## 7. Insecure Direct Object Reference (IDOR)
* **Where:** `vulnerable_archive/archiver/views.py` (`view_archive`, `edit_archive`, `delete_archive`, `enrich_archive` functions)
* **What:** Records were fetched using `get_object_or_404(Archive, pk=archive_id)` without validating ownership. Any authenticated user could interact with another user's archives simply by guessing or iterating the `archive_id`.
* **How it was fixed:** Appended an ownership requirement to the ORM lookup: `get_object_or_404(Archive, pk=archive_id, user=request.user)`. The application now throws a `404 Not Found` if a user attempts to access an unowned archive.

## 8. Stored Cross-Site Scripting (XSS)
* **Where:** `vulnerable_archive/archiver/templates/archiver/view_archive.html` (and other templates)
* **What:** Archive content and notes were rendered directly to the DOM using the Django `|safe` filter (`{{ archive.content|safe }}`). Malicious scripts injected during the archive creation process would execute in the browser of any user viewing the archive.
* **How it was fixed:** Stripped the `|safe` filter globally from all `.html` templates. Additionally, HTML encoding (`django.utils.html.escape`) was introduced at the ingestion layer (`add_archive`) as a defense-in-depth measure.

## 9. Debug Mode Enabled in Production
* **Where:** `vulnerable_archive/vulnerable_archive/settings.py` (Line 26)
* **What:** The application was running with `DEBUG = True`, which exposes highly sensitive traceback information, environmental variables, and internal code structures upon encountering an error.
* **How it was fixed:** Changed the configuration to load dynamically from the environment (`DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'`), safely defaulting to `False` while providing `ALLOWED_HOSTS = ["*"]` for compatibility.

## 10. LLM Prompt Injection
* **Where:** `vulnerable_archive/archiver/views.py` (`ask_database` function)
* **What:** The LLM prompt input field accepted raw instructions without bounds, allowing an attacker to inject system-level overrides (e.g., "Ignore previous instructions").
* **How it was fixed:** Introduced a deterministic regex/string filtering system that sanitizes the user's input against known jailbreak patterns before allowing the input to reach the LLM context window.

---

## Appendix: Security Justification Regarding Hardcoded Secrets
During the remediation process, you may notice that `fixes.patch` contains the plaintext removal of hardcoded secrets (e.g., `SECRET = "do_not_share_this"` and the Django `SECRET_KEY`).

While committing secrets to version control is typically a critical security violation, it is completely safe to commit this patch for two reasons:
1. **Educational Dummy Strings:** These strings are intentionally weak placeholders generated purely to serve as a vulnerable baseline for this demo application. They possess no real-world privileges or access.
2. **Existing Git History:** The strings are already embedded in the repository's Git history (which is how `git restore` successfully reverts to them). Obfuscating the patch file would not remove them from the underlying Git tree. In a real-world scenario, you would need to use tools like `git filter-repo` or BFG Repo-Cleaner to permanently scrub the history. Because this is a safe educational sandbox, committing the patch as-is is appropriate.

MD
echo "Remediation report generated at reports/vulnerability_remediation_report.md"
